apiVersion: apps/v1
kind: Deployment
metadata:
 name: streamlitweb
 labels:
   app: streamlit
spec:
 selector:
   matchLabels:
     app: streamlit
     tier: web
 template:
   metadata:
     labels:
       app: streamlit
       tier: web
   spec:
     containers:
      - name: streamlit-app
        image: cthiounn/my-streamlit-app
        ports:
        - containerPort: 8501
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"